
package soapservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.3
 * Tue Feb 11 10:51:55 CET 2014
 * Generated source version: 2.7.3
 */

@XmlRootElement(name = "getChosenVoyage", namespace = "http://soapservice/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getChosenVoyage", namespace = "http://soapservice/")

public class GetChosenVoyage {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

