
package fr.voyage.soapbdd;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2014-02-11T11:18:02.070+01:00
 * Generated source version: 2.7.3
 * 
 */
public final class RequestServer_RequestServerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soapservice/", "RequestServerService");

    private RequestServer_RequestServerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RequestServerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RequestServerService ss = new RequestServerService(wsdlURL, SERVICE_NAME);
        RequestServer port = ss.getRequestServerPort();  
        
        {
        System.out.println("Invoking getChosenVoyage...");
        java.lang.String _getChosenVoyage_arg0 = "_getChosenVoyage_arg0-1164938104";
        java.util.List<fr.voyage.soapbdd.Pair> _getChosenVoyage__return = port.getChosenVoyage(_getChosenVoyage_arg0);
        System.out.println("getChosenVoyage.result=" + _getChosenVoyage__return);


        }

        System.exit(0);
    }

}
