
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package soapservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2014-02-21T15:14:41.717+01:00
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "RequestServerService",
                      portName = "RequestServerPort",
                      targetNamespace = "http://soapservice/",
                      wsdlLocation = "http://localhost:8080/820SOAPVoyage/services/requestserver?wsdl",
                      endpointInterface = "soapservice.RequestServer")
                      
public class RequestServerImpl implements RequestServer {

    private static final Logger LOG = Logger.getLogger(RequestServerImpl.class.getName());

    /* (non-Javadoc)
     * @see soapservice.RequestServer#getChosenVoyage(java.lang.String  arg0 )*
     */
    public java.util.List<soapservice.Pair> getChosenVoyage(java.lang.String arg0) { 
        LOG.info("Executing operation getChosenVoyage");
        System.out.println(arg0);
        try {
            java.util.List<soapservice.Pair> _return = new java.util.ArrayList<soapservice.Pair>();
            soapservice.Pair _returnVal1 = new soapservice.Pair();
            java.lang.Object _returnVal1First = null;
            _returnVal1.setFirst(_returnVal1First);
            java.lang.Object _returnVal1Second = null;
            _returnVal1.setSecond(_returnVal1Second);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
