package soapservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2014-02-21T15:14:41.733+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://soapservice/", name = "RequestServer")
@XmlSeeAlso({ObjectFactory.class})
public interface RequestServer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getChosenVoyage", targetNamespace = "http://soapservice/", className = "soapservice.GetChosenVoyage")
    @WebMethod
    @ResponseWrapper(localName = "getChosenVoyageResponse", targetNamespace = "http://soapservice/", className = "soapservice.GetChosenVoyageResponse")
    public java.util.List<soapservice.Pair> getChosenVoyage(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
